

# Print tar contents:
# 1: Interpreted as relative to the root directory
# 2: With no trailing slashes on directories
# This is useful for ensuring that the output matches the
# values generated by the "find" command
ls_tar() {
  tar -tf $1 | xargs -d '\n' realpath -ms --relative-to=. | awk '{ if ($0 != ".") print "/"$0; }'
}


start_time() {
  echo -n "$1"
  start=`date +%s.%N`
}

end_time() {
  end=`date +%s.%N`
  tmp=$(echo "scale=2; $end - $start" | bc)
  echo " ($(printf "%.3g\n" $tmp)s)"
}
